// Code generated by ent, DO NOT EDIT.

package task

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCronExpression holds the string denoting the cron_expression field in the database.
	FieldCronExpression = "cron_expression"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldRunnerType holds the string denoting the runner_type field in the database.
	FieldRunnerType = "runner_type"
	// FieldRunnerConfig holds the string denoting the runner_config field in the database.
	FieldRunnerConfig = "runner_config"
	// FieldTimeoutSeconds holds the string denoting the timeout_seconds field in the database.
	FieldTimeoutSeconds = "timeout_seconds"
	// FieldOverlapPolicy holds the string denoting the overlap_policy field in the database.
	FieldOverlapPolicy = "overlap_policy"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRuns holds the string denoting the runs edge name in mutations.
	EdgeRuns = "runs"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// RunsTable is the table that holds the runs relation/edge.
	RunsTable = "runs"
	// RunsInverseTable is the table name for the Run entity.
	// It exists in this package in order to avoid circular dependency with the "run" package.
	RunsInverseTable = "runs"
	// RunsColumn is the table column denoting the runs relation/edge.
	RunsColumn = "task_runs"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldEnabled,
	FieldCronExpression,
	FieldTimezone,
	FieldRunnerType,
	FieldRunnerConfig,
	FieldTimeoutSeconds,
	FieldOverlapPolicy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// DefaultTimeoutSeconds holds the default value on creation for the "timeout_seconds" field.
	DefaultTimeoutSeconds int
	// TimeoutSecondsValidator is a validator for the "timeout_seconds" field. It is called by the builders before save.
	TimeoutSecondsValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// RunnerType defines the type for the "runner_type" enum field.
type RunnerType string

// RunnerTypeShell is the default value of the RunnerType enum.
const DefaultRunnerType = RunnerTypeShell

// RunnerType values.
const (
	RunnerTypeShell      RunnerType = "shell"
	RunnerTypeBash       RunnerType = "bash"
	RunnerTypePwsh       RunnerType = "pwsh"
	RunnerTypePython     RunnerType = "python"
	RunnerTypeNode       RunnerType = "node"
	RunnerTypeTypescript RunnerType = "typescript"
)

func (rt RunnerType) String() string {
	return string(rt)
}

// RunnerTypeValidator is a validator for the "runner_type" field enum values. It is called by the builders before save.
func RunnerTypeValidator(rt RunnerType) error {
	switch rt {
	case RunnerTypeShell, RunnerTypeBash, RunnerTypePwsh, RunnerTypePython, RunnerTypeNode, RunnerTypeTypescript:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for runner_type field: %q", rt)
	}
}

// OverlapPolicy defines the type for the "overlap_policy" enum field.
type OverlapPolicy string

// OverlapPolicySkip is the default value of the OverlapPolicy enum.
const DefaultOverlapPolicy = OverlapPolicySkip

// OverlapPolicy values.
const (
	OverlapPolicySkip OverlapPolicy = "skip"
)

func (op OverlapPolicy) String() string {
	return string(op)
}

// OverlapPolicyValidator is a validator for the "overlap_policy" field enum values. It is called by the builders before save.
func OverlapPolicyValidator(op OverlapPolicy) error {
	switch op {
	case OverlapPolicySkip:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for overlap_policy field: %q", op)
	}
}

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCronExpression orders the results by the cron_expression field.
func ByCronExpression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCronExpression, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByRunnerType orders the results by the runner_type field.
func ByRunnerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerType, opts...).ToFunc()
}

// ByTimeoutSeconds orders the results by the timeout_seconds field.
func ByTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutSeconds, opts...).ToFunc()
}

// ByOverlapPolicy orders the results by the overlap_policy field.
func ByOverlapPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverlapPolicy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRunsCount orders the results by runs count.
func ByRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRunsStep(), opts...)
	}
}

// ByRuns orders the results by runs terms.
func ByRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RunsTable, RunsColumn),
	)
}
