// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/predicate"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunUpdate is the builder for updating Run entities.
type RunUpdate struct {
	config
	hooks    []Hook
	mutation *RunMutation
}

// Where appends a list predicates to the RunUpdate builder.
func (ru *RunUpdate) Where(ps ...predicate.Run) *RunUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetTrigger sets the "trigger" field.
func (ru *RunUpdate) SetTrigger(r run.Trigger) *RunUpdate {
	ru.mutation.SetTrigger(r)
	return ru
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (ru *RunUpdate) SetNillableTrigger(r *run.Trigger) *RunUpdate {
	if r != nil {
		ru.SetTrigger(*r)
	}
	return ru
}

// SetStatus sets the "status" field.
func (ru *RunUpdate) SetStatus(r run.Status) *RunUpdate {
	ru.mutation.SetStatus(r)
	return ru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ru *RunUpdate) SetNillableStatus(r *run.Status) *RunUpdate {
	if r != nil {
		ru.SetStatus(*r)
	}
	return ru
}

// SetExitCode sets the "exit_code" field.
func (ru *RunUpdate) SetExitCode(i int) *RunUpdate {
	ru.mutation.ResetExitCode()
	ru.mutation.SetExitCode(i)
	return ru
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (ru *RunUpdate) SetNillableExitCode(i *int) *RunUpdate {
	if i != nil {
		ru.SetExitCode(*i)
	}
	return ru
}

// AddExitCode adds i to the "exit_code" field.
func (ru *RunUpdate) AddExitCode(i int) *RunUpdate {
	ru.mutation.AddExitCode(i)
	return ru
}

// ClearExitCode clears the value of the "exit_code" field.
func (ru *RunUpdate) ClearExitCode() *RunUpdate {
	ru.mutation.ClearExitCode()
	return ru
}

// SetStartedAt sets the "started_at" field.
func (ru *RunUpdate) SetStartedAt(t time.Time) *RunUpdate {
	ru.mutation.SetStartedAt(t)
	return ru
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (ru *RunUpdate) SetNillableStartedAt(t *time.Time) *RunUpdate {
	if t != nil {
		ru.SetStartedAt(*t)
	}
	return ru
}

// SetFinishedAt sets the "finished_at" field.
func (ru *RunUpdate) SetFinishedAt(t time.Time) *RunUpdate {
	ru.mutation.SetFinishedAt(t)
	return ru
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (ru *RunUpdate) SetNillableFinishedAt(t *time.Time) *RunUpdate {
	if t != nil {
		ru.SetFinishedAt(*t)
	}
	return ru
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (ru *RunUpdate) ClearFinishedAt() *RunUpdate {
	ru.mutation.ClearFinishedAt()
	return ru
}

// SetDurationMs sets the "duration_ms" field.
func (ru *RunUpdate) SetDurationMs(i int64) *RunUpdate {
	ru.mutation.ResetDurationMs()
	ru.mutation.SetDurationMs(i)
	return ru
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (ru *RunUpdate) SetNillableDurationMs(i *int64) *RunUpdate {
	if i != nil {
		ru.SetDurationMs(*i)
	}
	return ru
}

// AddDurationMs adds i to the "duration_ms" field.
func (ru *RunUpdate) AddDurationMs(i int64) *RunUpdate {
	ru.mutation.AddDurationMs(i)
	return ru
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (ru *RunUpdate) ClearDurationMs() *RunUpdate {
	ru.mutation.ClearDurationMs()
	return ru
}

// SetErrorSummary sets the "error_summary" field.
func (ru *RunUpdate) SetErrorSummary(s string) *RunUpdate {
	ru.mutation.SetErrorSummary(s)
	return ru
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (ru *RunUpdate) SetNillableErrorSummary(s *string) *RunUpdate {
	if s != nil {
		ru.SetErrorSummary(*s)
	}
	return ru
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (ru *RunUpdate) ClearErrorSummary() *RunUpdate {
	ru.mutation.ClearErrorSummary()
	return ru
}

// SetStdout sets the "stdout" field.
func (ru *RunUpdate) SetStdout(s string) *RunUpdate {
	ru.mutation.SetStdout(s)
	return ru
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (ru *RunUpdate) SetNillableStdout(s *string) *RunUpdate {
	if s != nil {
		ru.SetStdout(*s)
	}
	return ru
}

// ClearStdout clears the value of the "stdout" field.
func (ru *RunUpdate) ClearStdout() *RunUpdate {
	ru.mutation.ClearStdout()
	return ru
}

// SetStderr sets the "stderr" field.
func (ru *RunUpdate) SetStderr(s string) *RunUpdate {
	ru.mutation.SetStderr(s)
	return ru
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (ru *RunUpdate) SetNillableStderr(s *string) *RunUpdate {
	if s != nil {
		ru.SetStderr(*s)
	}
	return ru
}

// ClearStderr clears the value of the "stderr" field.
func (ru *RunUpdate) ClearStderr() *RunUpdate {
	ru.mutation.ClearStderr()
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *RunUpdate) SetUpdatedAt(t time.Time) *RunUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (ru *RunUpdate) SetTaskID(id int) *RunUpdate {
	ru.mutation.SetTaskID(id)
	return ru
}

// SetTask sets the "task" edge to the Task entity.
func (ru *RunUpdate) SetTask(t *Task) *RunUpdate {
	return ru.SetTaskID(t.ID)
}

// Mutation returns the RunMutation object of the builder.
func (ru *RunUpdate) Mutation() *RunMutation {
	return ru.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (ru *RunUpdate) ClearTask() *RunUpdate {
	ru.mutation.ClearTask()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RunUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RunUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RunUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RunUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RunUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := run.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RunUpdate) check() error {
	if v, ok := ru.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	if _, ok := ru.mutation.TaskID(); ru.mutation.TaskCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Run.task"`)
	}
	return nil
}

func (ru *RunUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ru.mutation.ExitCode(); ok {
		_spec.SetField(run.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedExitCode(); ok {
		_spec.AddField(run.FieldExitCode, field.TypeInt, value)
	}
	if ru.mutation.ExitCodeCleared() {
		_spec.ClearField(run.FieldExitCode, field.TypeInt)
	}
	if value, ok := ru.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := ru.mutation.FinishedAt(); ok {
		_spec.SetField(run.FieldFinishedAt, field.TypeTime, value)
	}
	if ru.mutation.FinishedAtCleared() {
		_spec.ClearField(run.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := ru.mutation.DurationMs(); ok {
		_spec.SetField(run.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := ru.mutation.AddedDurationMs(); ok {
		_spec.AddField(run.FieldDurationMs, field.TypeInt64, value)
	}
	if ru.mutation.DurationMsCleared() {
		_spec.ClearField(run.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := ru.mutation.ErrorSummary(); ok {
		_spec.SetField(run.FieldErrorSummary, field.TypeString, value)
	}
	if ru.mutation.ErrorSummaryCleared() {
		_spec.ClearField(run.FieldErrorSummary, field.TypeString)
	}
	if value, ok := ru.mutation.Stdout(); ok {
		_spec.SetField(run.FieldStdout, field.TypeString, value)
	}
	if ru.mutation.StdoutCleared() {
		_spec.ClearField(run.FieldStdout, field.TypeString)
	}
	if value, ok := ru.mutation.Stderr(); ok {
		_spec.SetField(run.FieldStderr, field.TypeString, value)
	}
	if ru.mutation.StderrCleared() {
		_spec.ClearField(run.FieldStderr, field.TypeString)
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if ru.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RunUpdateOne is the builder for updating a single Run entity.
type RunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunMutation
}

// SetTrigger sets the "trigger" field.
func (ruo *RunUpdateOne) SetTrigger(r run.Trigger) *RunUpdateOne {
	ruo.mutation.SetTrigger(r)
	return ruo
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableTrigger(r *run.Trigger) *RunUpdateOne {
	if r != nil {
		ruo.SetTrigger(*r)
	}
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *RunUpdateOne) SetStatus(r run.Status) *RunUpdateOne {
	ruo.mutation.SetStatus(r)
	return ruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableStatus(r *run.Status) *RunUpdateOne {
	if r != nil {
		ruo.SetStatus(*r)
	}
	return ruo
}

// SetExitCode sets the "exit_code" field.
func (ruo *RunUpdateOne) SetExitCode(i int) *RunUpdateOne {
	ruo.mutation.ResetExitCode()
	ruo.mutation.SetExitCode(i)
	return ruo
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableExitCode(i *int) *RunUpdateOne {
	if i != nil {
		ruo.SetExitCode(*i)
	}
	return ruo
}

// AddExitCode adds i to the "exit_code" field.
func (ruo *RunUpdateOne) AddExitCode(i int) *RunUpdateOne {
	ruo.mutation.AddExitCode(i)
	return ruo
}

// ClearExitCode clears the value of the "exit_code" field.
func (ruo *RunUpdateOne) ClearExitCode() *RunUpdateOne {
	ruo.mutation.ClearExitCode()
	return ruo
}

// SetStartedAt sets the "started_at" field.
func (ruo *RunUpdateOne) SetStartedAt(t time.Time) *RunUpdateOne {
	ruo.mutation.SetStartedAt(t)
	return ruo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableStartedAt(t *time.Time) *RunUpdateOne {
	if t != nil {
		ruo.SetStartedAt(*t)
	}
	return ruo
}

// SetFinishedAt sets the "finished_at" field.
func (ruo *RunUpdateOne) SetFinishedAt(t time.Time) *RunUpdateOne {
	ruo.mutation.SetFinishedAt(t)
	return ruo
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableFinishedAt(t *time.Time) *RunUpdateOne {
	if t != nil {
		ruo.SetFinishedAt(*t)
	}
	return ruo
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (ruo *RunUpdateOne) ClearFinishedAt() *RunUpdateOne {
	ruo.mutation.ClearFinishedAt()
	return ruo
}

// SetDurationMs sets the "duration_ms" field.
func (ruo *RunUpdateOne) SetDurationMs(i int64) *RunUpdateOne {
	ruo.mutation.ResetDurationMs()
	ruo.mutation.SetDurationMs(i)
	return ruo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableDurationMs(i *int64) *RunUpdateOne {
	if i != nil {
		ruo.SetDurationMs(*i)
	}
	return ruo
}

// AddDurationMs adds i to the "duration_ms" field.
func (ruo *RunUpdateOne) AddDurationMs(i int64) *RunUpdateOne {
	ruo.mutation.AddDurationMs(i)
	return ruo
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (ruo *RunUpdateOne) ClearDurationMs() *RunUpdateOne {
	ruo.mutation.ClearDurationMs()
	return ruo
}

// SetErrorSummary sets the "error_summary" field.
func (ruo *RunUpdateOne) SetErrorSummary(s string) *RunUpdateOne {
	ruo.mutation.SetErrorSummary(s)
	return ruo
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableErrorSummary(s *string) *RunUpdateOne {
	if s != nil {
		ruo.SetErrorSummary(*s)
	}
	return ruo
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (ruo *RunUpdateOne) ClearErrorSummary() *RunUpdateOne {
	ruo.mutation.ClearErrorSummary()
	return ruo
}

// SetStdout sets the "stdout" field.
func (ruo *RunUpdateOne) SetStdout(s string) *RunUpdateOne {
	ruo.mutation.SetStdout(s)
	return ruo
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableStdout(s *string) *RunUpdateOne {
	if s != nil {
		ruo.SetStdout(*s)
	}
	return ruo
}

// ClearStdout clears the value of the "stdout" field.
func (ruo *RunUpdateOne) ClearStdout() *RunUpdateOne {
	ruo.mutation.ClearStdout()
	return ruo
}

// SetStderr sets the "stderr" field.
func (ruo *RunUpdateOne) SetStderr(s string) *RunUpdateOne {
	ruo.mutation.SetStderr(s)
	return ruo
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (ruo *RunUpdateOne) SetNillableStderr(s *string) *RunUpdateOne {
	if s != nil {
		ruo.SetStderr(*s)
	}
	return ruo
}

// ClearStderr clears the value of the "stderr" field.
func (ruo *RunUpdateOne) ClearStderr() *RunUpdateOne {
	ruo.mutation.ClearStderr()
	return ruo
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *RunUpdateOne) SetUpdatedAt(t time.Time) *RunUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (ruo *RunUpdateOne) SetTaskID(id int) *RunUpdateOne {
	ruo.mutation.SetTaskID(id)
	return ruo
}

// SetTask sets the "task" edge to the Task entity.
func (ruo *RunUpdateOne) SetTask(t *Task) *RunUpdateOne {
	return ruo.SetTaskID(t.ID)
}

// Mutation returns the RunMutation object of the builder.
func (ruo *RunUpdateOne) Mutation() *RunMutation {
	return ruo.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (ruo *RunUpdateOne) ClearTask() *RunUpdateOne {
	ruo.mutation.ClearTask()
	return ruo
}

// Where appends a list predicates to the RunUpdate builder.
func (ruo *RunUpdateOne) Where(ps ...predicate.Run) *RunUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RunUpdateOne) Select(field string, fields ...string) *RunUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Run entity.
func (ruo *RunUpdateOne) Save(ctx context.Context) (*Run, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RunUpdateOne) SaveX(ctx context.Context) *Run {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RunUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RunUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RunUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := run.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RunUpdateOne) check() error {
	if v, ok := ruo.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	if _, ok := ruo.mutation.TaskID(); ruo.mutation.TaskCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Run.task"`)
	}
	return nil
}

func (ruo *RunUpdateOne) sqlSave(ctx context.Context) (_node *Run, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Run.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, run.FieldID)
		for _, f := range fields {
			if !run.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != run.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ruo.mutation.ExitCode(); ok {
		_spec.SetField(run.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedExitCode(); ok {
		_spec.AddField(run.FieldExitCode, field.TypeInt, value)
	}
	if ruo.mutation.ExitCodeCleared() {
		_spec.ClearField(run.FieldExitCode, field.TypeInt)
	}
	if value, ok := ruo.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.FinishedAt(); ok {
		_spec.SetField(run.FieldFinishedAt, field.TypeTime, value)
	}
	if ruo.mutation.FinishedAtCleared() {
		_spec.ClearField(run.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := ruo.mutation.DurationMs(); ok {
		_spec.SetField(run.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := ruo.mutation.AddedDurationMs(); ok {
		_spec.AddField(run.FieldDurationMs, field.TypeInt64, value)
	}
	if ruo.mutation.DurationMsCleared() {
		_spec.ClearField(run.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := ruo.mutation.ErrorSummary(); ok {
		_spec.SetField(run.FieldErrorSummary, field.TypeString, value)
	}
	if ruo.mutation.ErrorSummaryCleared() {
		_spec.ClearField(run.FieldErrorSummary, field.TypeString)
	}
	if value, ok := ruo.mutation.Stdout(); ok {
		_spec.SetField(run.FieldStdout, field.TypeString, value)
	}
	if ruo.mutation.StdoutCleared() {
		_spec.ClearField(run.FieldStdout, field.TypeString)
	}
	if value, ok := ruo.mutation.Stderr(); ok {
		_spec.SetField(run.FieldStderr, field.TypeString, value)
	}
	if ruo.mutation.StderrCleared() {
		_spec.ClearField(run.FieldStderr, field.TypeString)
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if ruo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Run{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
