// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminsColumns holds the columns for the "admins" table.
	AdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "singleton_key", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminsTable holds the schema information for the "admins" table.
	AdminsTable = &schema.Table{
		Name:       "admins",
		Columns:    AdminsColumns,
		PrimaryKey: []*schema.Column{AdminsColumns[0]},
	}
	// AudioRecordsColumns holds the columns for the "audio_records" table.
	AudioRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_kind", Type: field.TypeEnum, Enums: []string{"url", "upload"}, Default: "url"},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "source_url", Type: field.TypeString, Nullable: true},
		{Name: "original_filename", Type: field.TypeString, Nullable: true},
		{Name: "stored_path", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString, Nullable: true},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "sha256", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"received", "queued", "playing", "played", "failed", "skipped", "queued_skipped"}, Default: "received"},
		{Name: "error_summary", Type: field.TypeString, Nullable: true},
		{Name: "played_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AudioRecordsTable holds the schema information for the "audio_records" table.
	AudioRecordsTable = &schema.Table{
		Name:       "audio_records",
		Columns:    AudioRecordsColumns,
		PrimaryKey: []*schema.Column{AudioRecordsColumns[0]},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "severity", Type: field.TypeEnum, Enums: []string{"info", "warning", "error", "critical"}},
		{Name: "subject_kind", Type: field.TypeString, Nullable: true},
		{Name: "subject_id", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_read_at_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[9], NotificationsColumns[10]},
			},
			{
				Name:    "notification_severity_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[3], NotificationsColumns[10]},
			},
		},
	}
	// RunsColumns holds the columns for the "runs" table.
	RunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"cron", "manual"}, Default: "cron"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"queued", "running", "success", "failed", "timeout", "cancelled", "skipped"}, Default: "queued"},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "error_summary", Type: field.TypeString, Nullable: true},
		{Name: "stdout", Type: field.TypeString, Nullable: true},
		{Name: "stderr", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "task_runs", Type: field.TypeInt},
	}
	// RunsTable holds the schema information for the "runs" table.
	RunsTable = &schema.Table{
		Name:       "runs",
		Columns:    RunsColumns,
		PrimaryKey: []*schema.Column{RunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "runs_tasks_runs",
				Columns:    []*schema.Column{RunsColumns[12]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "csrf_token_hash", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "admin_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_admins_sessions",
				Columns:    []*schema.Column{SessionsColumns[8]},
				RefColumns: []*schema.Column{AdminsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "cron_expression", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "Local"},
		{Name: "runner_type", Type: field.TypeEnum, Enums: []string{"shell", "bash", "pwsh", "python", "node", "typescript"}, Default: "shell"},
		{Name: "runner_config", Type: field.TypeJSON, Nullable: true},
		{Name: "timeout_seconds", Type: field.TypeInt, Default: 3600},
		{Name: "overlap_policy", Type: field.TypeEnum, Enums: []string{"skip"}, Default: "skip"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminsTable,
		AudioRecordsTable,
		NotificationsTable,
		RunsTable,
		SessionsTable,
		TasksTable,
	}
)

func init() {
	RunsTable.ForeignKeys[0].RefTable = TasksTable
	SessionsTable.ForeignKeys[0].RefTable = AdminsTable
}
