// Code generated by ent, DO NOT EDIT.

package run

import (
	"taskdaemon/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldID, id))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldExitCode, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldFinishedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorSummary applies equality check predicate on the "error_summary" field. It's identical to ErrorSummaryEQ.
func ErrorSummary(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldErrorSummary, v))
}

// Stdout applies equality check predicate on the "stdout" field. It's identical to StdoutEQ.
func Stdout(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStdout, v))
}

// Stderr applies equality check predicate on the "stderr" field. It's identical to StderrEQ.
func Stderr(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStderr, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldUpdatedAt, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v Trigger) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v Trigger) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...Trigger) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...Trigger) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldTrigger, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldStatus, vs...))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldExitCode, v))
}

// ExitCodeIsNil applies the IsNil predicate on the "exit_code" field.
func ExitCodeIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldExitCode))
}

// ExitCodeNotNil applies the NotNil predicate on the "exit_code" field.
func ExitCodeNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldExitCode))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldFinishedAt))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldDurationMs))
}

// ErrorSummaryEQ applies the EQ predicate on the "error_summary" field.
func ErrorSummaryEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldErrorSummary, v))
}

// ErrorSummaryNEQ applies the NEQ predicate on the "error_summary" field.
func ErrorSummaryNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldErrorSummary, v))
}

// ErrorSummaryIn applies the In predicate on the "error_summary" field.
func ErrorSummaryIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldErrorSummary, vs...))
}

// ErrorSummaryNotIn applies the NotIn predicate on the "error_summary" field.
func ErrorSummaryNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldErrorSummary, vs...))
}

// ErrorSummaryGT applies the GT predicate on the "error_summary" field.
func ErrorSummaryGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldErrorSummary, v))
}

// ErrorSummaryGTE applies the GTE predicate on the "error_summary" field.
func ErrorSummaryGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldErrorSummary, v))
}

// ErrorSummaryLT applies the LT predicate on the "error_summary" field.
func ErrorSummaryLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldErrorSummary, v))
}

// ErrorSummaryLTE applies the LTE predicate on the "error_summary" field.
func ErrorSummaryLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldErrorSummary, v))
}

// ErrorSummaryContains applies the Contains predicate on the "error_summary" field.
func ErrorSummaryContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldErrorSummary, v))
}

// ErrorSummaryHasPrefix applies the HasPrefix predicate on the "error_summary" field.
func ErrorSummaryHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldErrorSummary, v))
}

// ErrorSummaryHasSuffix applies the HasSuffix predicate on the "error_summary" field.
func ErrorSummaryHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldErrorSummary, v))
}

// ErrorSummaryIsNil applies the IsNil predicate on the "error_summary" field.
func ErrorSummaryIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldErrorSummary))
}

// ErrorSummaryNotNil applies the NotNil predicate on the "error_summary" field.
func ErrorSummaryNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldErrorSummary))
}

// ErrorSummaryEqualFold applies the EqualFold predicate on the "error_summary" field.
func ErrorSummaryEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldErrorSummary, v))
}

// ErrorSummaryContainsFold applies the ContainsFold predicate on the "error_summary" field.
func ErrorSummaryContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldErrorSummary, v))
}

// StdoutEQ applies the EQ predicate on the "stdout" field.
func StdoutEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStdout, v))
}

// StdoutNEQ applies the NEQ predicate on the "stdout" field.
func StdoutNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldStdout, v))
}

// StdoutIn applies the In predicate on the "stdout" field.
func StdoutIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldStdout, vs...))
}

// StdoutNotIn applies the NotIn predicate on the "stdout" field.
func StdoutNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldStdout, vs...))
}

// StdoutGT applies the GT predicate on the "stdout" field.
func StdoutGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldStdout, v))
}

// StdoutGTE applies the GTE predicate on the "stdout" field.
func StdoutGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldStdout, v))
}

// StdoutLT applies the LT predicate on the "stdout" field.
func StdoutLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldStdout, v))
}

// StdoutLTE applies the LTE predicate on the "stdout" field.
func StdoutLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldStdout, v))
}

// StdoutContains applies the Contains predicate on the "stdout" field.
func StdoutContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldStdout, v))
}

// StdoutHasPrefix applies the HasPrefix predicate on the "stdout" field.
func StdoutHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldStdout, v))
}

// StdoutHasSuffix applies the HasSuffix predicate on the "stdout" field.
func StdoutHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldStdout, v))
}

// StdoutIsNil applies the IsNil predicate on the "stdout" field.
func StdoutIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldStdout))
}

// StdoutNotNil applies the NotNil predicate on the "stdout" field.
func StdoutNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldStdout))
}

// StdoutEqualFold applies the EqualFold predicate on the "stdout" field.
func StdoutEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldStdout, v))
}

// StdoutContainsFold applies the ContainsFold predicate on the "stdout" field.
func StdoutContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldStdout, v))
}

// StderrEQ applies the EQ predicate on the "stderr" field.
func StderrEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldStderr, v))
}

// StderrNEQ applies the NEQ predicate on the "stderr" field.
func StderrNEQ(v string) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldStderr, v))
}

// StderrIn applies the In predicate on the "stderr" field.
func StderrIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldStderr, vs...))
}

// StderrNotIn applies the NotIn predicate on the "stderr" field.
func StderrNotIn(vs ...string) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldStderr, vs...))
}

// StderrGT applies the GT predicate on the "stderr" field.
func StderrGT(v string) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldStderr, v))
}

// StderrGTE applies the GTE predicate on the "stderr" field.
func StderrGTE(v string) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldStderr, v))
}

// StderrLT applies the LT predicate on the "stderr" field.
func StderrLT(v string) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldStderr, v))
}

// StderrLTE applies the LTE predicate on the "stderr" field.
func StderrLTE(v string) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldStderr, v))
}

// StderrContains applies the Contains predicate on the "stderr" field.
func StderrContains(v string) predicate.Run {
	return predicate.Run(sql.FieldContains(FieldStderr, v))
}

// StderrHasPrefix applies the HasPrefix predicate on the "stderr" field.
func StderrHasPrefix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasPrefix(FieldStderr, v))
}

// StderrHasSuffix applies the HasSuffix predicate on the "stderr" field.
func StderrHasSuffix(v string) predicate.Run {
	return predicate.Run(sql.FieldHasSuffix(FieldStderr, v))
}

// StderrIsNil applies the IsNil predicate on the "stderr" field.
func StderrIsNil() predicate.Run {
	return predicate.Run(sql.FieldIsNull(FieldStderr))
}

// StderrNotNil applies the NotNil predicate on the "stderr" field.
func StderrNotNil() predicate.Run {
	return predicate.Run(sql.FieldNotNull(FieldStderr))
}

// StderrEqualFold applies the EqualFold predicate on the "stderr" field.
func StderrEqualFold(v string) predicate.Run {
	return predicate.Run(sql.FieldEqualFold(FieldStderr, v))
}

// StderrContainsFold applies the ContainsFold predicate on the "stderr" field.
func StderrContainsFold(v string) predicate.Run {
	return predicate.Run(sql.FieldContainsFold(FieldStderr, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Run {
	return predicate.Run(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Run {
	return predicate.Run(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.Run {
	return predicate.Run(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.Run {
	return predicate.Run(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Run) predicate.Run {
	return predicate.Run(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Run) predicate.Run {
	return predicate.Run(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Run) predicate.Run {
	return predicate.Run(sql.NotPredicates(p))
}
