// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/audiorecord"
	"taskdaemon/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AudioRecordUpdate is the builder for updating AudioRecord entities.
type AudioRecordUpdate struct {
	config
	hooks    []Hook
	mutation *AudioRecordMutation
}

// Where appends a list predicates to the AudioRecordUpdate builder.
func (_u *AudioRecordUpdate) Where(ps ...predicate.AudioRecord) *AudioRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceKind sets the "source_kind" field.
func (_u *AudioRecordUpdate) SetSourceKind(v audiorecord.SourceKind) *AudioRecordUpdate {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableSourceKind(v *audiorecord.SourceKind) *AudioRecordUpdate {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AudioRecordUpdate) SetSource(v string) *AudioRecordUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableSource(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *AudioRecordUpdate) ClearSource() *AudioRecordUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *AudioRecordUpdate) SetSourceURL(v string) *AudioRecordUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableSourceURL(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *AudioRecordUpdate) ClearSourceURL() *AudioRecordUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AudioRecordUpdate) SetOriginalFilename(v string) *AudioRecordUpdate {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableOriginalFilename(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *AudioRecordUpdate) ClearOriginalFilename() *AudioRecordUpdate {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// SetStoredPath sets the "stored_path" field.
func (_u *AudioRecordUpdate) SetStoredPath(v string) *AudioRecordUpdate {
	_u.mutation.SetStoredPath(v)
	return _u
}

// SetNillableStoredPath sets the "stored_path" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableStoredPath(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetStoredPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AudioRecordUpdate) SetMimeType(v string) *AudioRecordUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableMimeType(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *AudioRecordUpdate) ClearMimeType() *AudioRecordUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AudioRecordUpdate) SetSizeBytes(v int64) *AudioRecordUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableSizeBytes(v *int64) *AudioRecordUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AudioRecordUpdate) AddSizeBytes(v int64) *AudioRecordUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *AudioRecordUpdate) SetSha256(v string) *AudioRecordUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableSha256(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AudioRecordUpdate) SetStatus(v audiorecord.Status) *AudioRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableStatus(v *audiorecord.Status) *AudioRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorSummary sets the "error_summary" field.
func (_u *AudioRecordUpdate) SetErrorSummary(v string) *AudioRecordUpdate {
	_u.mutation.SetErrorSummary(v)
	return _u
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillableErrorSummary(v *string) *AudioRecordUpdate {
	if v != nil {
		_u.SetErrorSummary(*v)
	}
	return _u
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (_u *AudioRecordUpdate) ClearErrorSummary() *AudioRecordUpdate {
	_u.mutation.ClearErrorSummary()
	return _u
}

// SetPlayedAt sets the "played_at" field.
func (_u *AudioRecordUpdate) SetPlayedAt(v time.Time) *AudioRecordUpdate {
	_u.mutation.SetPlayedAt(v)
	return _u
}

// SetNillablePlayedAt sets the "played_at" field if the given value is not nil.
func (_u *AudioRecordUpdate) SetNillablePlayedAt(v *time.Time) *AudioRecordUpdate {
	if v != nil {
		_u.SetPlayedAt(*v)
	}
	return _u
}

// ClearPlayedAt clears the value of the "played_at" field.
func (_u *AudioRecordUpdate) ClearPlayedAt() *AudioRecordUpdate {
	_u.mutation.ClearPlayedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AudioRecordUpdate) SetUpdatedAt(v time.Time) *AudioRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AudioRecordMutation object of the builder.
func (_u *AudioRecordUpdate) Mutation() *AudioRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AudioRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AudioRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AudioRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AudioRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AudioRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := audiorecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AudioRecordUpdate) check() error {
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := audiorecord.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.source_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoredPath(); ok {
		if err := audiorecord.StoredPathValidator(v); err != nil {
			return &ValidationError{Name: "stored_path", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.stored_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := audiorecord.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := audiorecord.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := audiorecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AudioRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audiorecord.Table, audiorecord.Columns, sqlgraph.NewFieldSpec(audiorecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(audiorecord.FieldSourceKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(audiorecord.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(audiorecord.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(audiorecord.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(audiorecord.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(audiorecord.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(audiorecord.FieldOriginalFilename, field.TypeString)
	}
	if value, ok := _u.mutation.StoredPath(); ok {
		_spec.SetField(audiorecord.FieldStoredPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(audiorecord.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(audiorecord.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(audiorecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(audiorecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(audiorecord.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(audiorecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorSummary(); ok {
		_spec.SetField(audiorecord.FieldErrorSummary, field.TypeString, value)
	}
	if _u.mutation.ErrorSummaryCleared() {
		_spec.ClearField(audiorecord.FieldErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.PlayedAt(); ok {
		_spec.SetField(audiorecord.FieldPlayedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayedAtCleared() {
		_spec.ClearField(audiorecord.FieldPlayedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(audiorecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audiorecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AudioRecordUpdateOne is the builder for updating a single AudioRecord entity.
type AudioRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AudioRecordMutation
}

// SetSourceKind sets the "source_kind" field.
func (_u *AudioRecordUpdateOne) SetSourceKind(v audiorecord.SourceKind) *AudioRecordUpdateOne {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableSourceKind(v *audiorecord.SourceKind) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AudioRecordUpdateOne) SetSource(v string) *AudioRecordUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableSource(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *AudioRecordUpdateOne) ClearSource() *AudioRecordUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *AudioRecordUpdateOne) SetSourceURL(v string) *AudioRecordUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableSourceURL(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *AudioRecordUpdateOne) ClearSourceURL() *AudioRecordUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AudioRecordUpdateOne) SetOriginalFilename(v string) *AudioRecordUpdateOne {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableOriginalFilename(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *AudioRecordUpdateOne) ClearOriginalFilename() *AudioRecordUpdateOne {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// SetStoredPath sets the "stored_path" field.
func (_u *AudioRecordUpdateOne) SetStoredPath(v string) *AudioRecordUpdateOne {
	_u.mutation.SetStoredPath(v)
	return _u
}

// SetNillableStoredPath sets the "stored_path" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableStoredPath(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetStoredPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AudioRecordUpdateOne) SetMimeType(v string) *AudioRecordUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableMimeType(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *AudioRecordUpdateOne) ClearMimeType() *AudioRecordUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AudioRecordUpdateOne) SetSizeBytes(v int64) *AudioRecordUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableSizeBytes(v *int64) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AudioRecordUpdateOne) AddSizeBytes(v int64) *AudioRecordUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *AudioRecordUpdateOne) SetSha256(v string) *AudioRecordUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableSha256(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AudioRecordUpdateOne) SetStatus(v audiorecord.Status) *AudioRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableStatus(v *audiorecord.Status) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorSummary sets the "error_summary" field.
func (_u *AudioRecordUpdateOne) SetErrorSummary(v string) *AudioRecordUpdateOne {
	_u.mutation.SetErrorSummary(v)
	return _u
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillableErrorSummary(v *string) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetErrorSummary(*v)
	}
	return _u
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (_u *AudioRecordUpdateOne) ClearErrorSummary() *AudioRecordUpdateOne {
	_u.mutation.ClearErrorSummary()
	return _u
}

// SetPlayedAt sets the "played_at" field.
func (_u *AudioRecordUpdateOne) SetPlayedAt(v time.Time) *AudioRecordUpdateOne {
	_u.mutation.SetPlayedAt(v)
	return _u
}

// SetNillablePlayedAt sets the "played_at" field if the given value is not nil.
func (_u *AudioRecordUpdateOne) SetNillablePlayedAt(v *time.Time) *AudioRecordUpdateOne {
	if v != nil {
		_u.SetPlayedAt(*v)
	}
	return _u
}

// ClearPlayedAt clears the value of the "played_at" field.
func (_u *AudioRecordUpdateOne) ClearPlayedAt() *AudioRecordUpdateOne {
	_u.mutation.ClearPlayedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AudioRecordUpdateOne) SetUpdatedAt(v time.Time) *AudioRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AudioRecordMutation object of the builder.
func (_u *AudioRecordUpdateOne) Mutation() *AudioRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the AudioRecordUpdate builder.
func (_u *AudioRecordUpdateOne) Where(ps ...predicate.AudioRecord) *AudioRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AudioRecordUpdateOne) Select(field string, fields ...string) *AudioRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AudioRecord entity.
func (_u *AudioRecordUpdateOne) Save(ctx context.Context) (*AudioRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AudioRecordUpdateOne) SaveX(ctx context.Context) *AudioRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AudioRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AudioRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AudioRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := audiorecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AudioRecordUpdateOne) check() error {
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := audiorecord.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.source_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoredPath(); ok {
		if err := audiorecord.StoredPathValidator(v); err != nil {
			return &ValidationError{Name: "stored_path", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.stored_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := audiorecord.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := audiorecord.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := audiorecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AudioRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AudioRecordUpdateOne) sqlSave(ctx context.Context) (_node *AudioRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audiorecord.Table, audiorecord.Columns, sqlgraph.NewFieldSpec(audiorecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AudioRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audiorecord.FieldID)
		for _, f := range fields {
			if !audiorecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != audiorecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(audiorecord.FieldSourceKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(audiorecord.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(audiorecord.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(audiorecord.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(audiorecord.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(audiorecord.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(audiorecord.FieldOriginalFilename, field.TypeString)
	}
	if value, ok := _u.mutation.StoredPath(); ok {
		_spec.SetField(audiorecord.FieldStoredPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(audiorecord.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(audiorecord.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(audiorecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(audiorecord.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(audiorecord.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(audiorecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorSummary(); ok {
		_spec.SetField(audiorecord.FieldErrorSummary, field.TypeString, value)
	}
	if _u.mutation.ErrorSummaryCleared() {
		_spec.ClearField(audiorecord.FieldErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.PlayedAt(); ok {
		_spec.SetField(audiorecord.FieldPlayedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayedAtCleared() {
		_spec.ClearField(audiorecord.FieldPlayedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(audiorecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AudioRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audiorecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
