// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskdaemon/internal/data/ent/audiorecord"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AudioRecord is the model entity for the AudioRecord schema.
type AudioRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceKind holds the value of the "source_kind" field.
	SourceKind audiorecord.SourceKind `json:"source_kind,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"-"`
	// OriginalFilename holds the value of the "original_filename" field.
	OriginalFilename string `json:"original_filename,omitempty"`
	// StoredPath holds the value of the "stored_path" field.
	StoredPath string `json:"stored_path,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// Status holds the value of the "status" field.
	Status audiorecord.Status `json:"status,omitempty"`
	// ErrorSummary holds the value of the "error_summary" field.
	ErrorSummary string `json:"error_summary,omitempty"`
	// PlayedAt holds the value of the "played_at" field.
	PlayedAt *time.Time `json:"played_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AudioRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case audiorecord.FieldID, audiorecord.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case audiorecord.FieldSourceKind, audiorecord.FieldSource, audiorecord.FieldSourceURL, audiorecord.FieldOriginalFilename, audiorecord.FieldStoredPath, audiorecord.FieldMimeType, audiorecord.FieldSha256, audiorecord.FieldStatus, audiorecord.FieldErrorSummary:
			values[i] = new(sql.NullString)
		case audiorecord.FieldPlayedAt, audiorecord.FieldCreatedAt, audiorecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AudioRecord fields.
func (_m *AudioRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case audiorecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case audiorecord.FieldSourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_kind", values[i])
			} else if value.Valid {
				_m.SourceKind = audiorecord.SourceKind(value.String)
			}
		case audiorecord.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case audiorecord.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case audiorecord.FieldOriginalFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_filename", values[i])
			} else if value.Valid {
				_m.OriginalFilename = value.String
			}
		case audiorecord.FieldStoredPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stored_path", values[i])
			} else if value.Valid {
				_m.StoredPath = value.String
			}
		case audiorecord.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case audiorecord.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case audiorecord.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case audiorecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = audiorecord.Status(value.String)
			}
		case audiorecord.FieldErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_summary", values[i])
			} else if value.Valid {
				_m.ErrorSummary = value.String
			}
		case audiorecord.FieldPlayedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field played_at", values[i])
			} else if value.Valid {
				_m.PlayedAt = new(time.Time)
				*_m.PlayedAt = value.Time
			}
		case audiorecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case audiorecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AudioRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AudioRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AudioRecord.
// Note that you need to call AudioRecord.Unwrap() before calling this method if this AudioRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AudioRecord) Update() *AudioRecordUpdateOne {
	return NewAudioRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AudioRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AudioRecord) Unwrap() *AudioRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AudioRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AudioRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AudioRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceKind))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_url=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("original_filename=")
	builder.WriteString(_m.OriginalFilename)
	builder.WriteString(", ")
	builder.WriteString("stored_path=")
	builder.WriteString(_m.StoredPath)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error_summary=")
	builder.WriteString(_m.ErrorSummary)
	builder.WriteString(", ")
	if v := _m.PlayedAt; v != nil {
		builder.WriteString("played_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AudioRecords is a parsable slice of AudioRecord.
type AudioRecords []*AudioRecord
