// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Run is the model entity for the Run schema.
type Run struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger run.Trigger `json:"trigger,omitempty"`
	// Status holds the value of the "status" field.
	Status run.Status `json:"status,omitempty"`
	// ExitCode holds the value of the "exit_code" field.
	ExitCode *int `json:"exit_code,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// ErrorSummary holds the value of the "error_summary" field.
	ErrorSummary string `json:"error_summary,omitempty"`
	// Stdout holds the value of the "stdout" field.
	Stdout string `json:"stdout,omitempty"`
	// Stderr holds the value of the "stderr" field.
	Stderr string `json:"stderr,omitempty"`
	// LogArchiveStatus holds the value of the "log_archive_status" field.
	LogArchiveStatus run.LogArchiveStatus `json:"log_archive_status,omitempty"`
	// LogSizeBytes holds the value of the "log_size_bytes" field.
	LogSizeBytes *int64 `json:"log_size_bytes,omitempty"`
	// LogWriteFailed holds the value of the "log_write_failed" field.
	LogWriteFailed bool `json:"log_write_failed,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RunQuery when eager-loading is set.
	Edges        RunEdges `json:"edges"`
	task_runs    *int
	selectValues sql.SelectValues
}

// RunEdges holds the relations/edges for other nodes in the graph.
type RunEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RunEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Run) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case run.FieldLogWriteFailed:
			values[i] = new(sql.NullBool)
		case run.FieldID, run.FieldExitCode, run.FieldDurationMs, run.FieldLogSizeBytes:
			values[i] = new(sql.NullInt64)
		case run.FieldTrigger, run.FieldStatus, run.FieldErrorSummary, run.FieldStdout, run.FieldStderr, run.FieldLogArchiveStatus:
			values[i] = new(sql.NullString)
		case run.FieldStartedAt, run.FieldFinishedAt, run.FieldCreatedAt, run.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case run.ForeignKeys[0]: // task_runs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Run fields.
func (_m *Run) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case run.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = run.Trigger(value.String)
			}
		case run.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = run.Status(value.String)
			}
		case run.FieldExitCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exit_code", values[i])
			} else if value.Valid {
				_m.ExitCode = new(int)
				*_m.ExitCode = int(value.Int64)
			}
		case run.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case run.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case run.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case run.FieldErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_summary", values[i])
			} else if value.Valid {
				_m.ErrorSummary = value.String
			}
		case run.FieldStdout:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stdout", values[i])
			} else if value.Valid {
				_m.Stdout = value.String
			}
		case run.FieldStderr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stderr", values[i])
			} else if value.Valid {
				_m.Stderr = value.String
			}
		case run.FieldLogArchiveStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_archive_status", values[i])
			} else if value.Valid {
				_m.LogArchiveStatus = run.LogArchiveStatus(value.String)
			}
		case run.FieldLogSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field log_size_bytes", values[i])
			} else if value.Valid {
				_m.LogSizeBytes = new(int64)
				*_m.LogSizeBytes = value.Int64
			}
		case run.FieldLogWriteFailed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field log_write_failed", values[i])
			} else if value.Valid {
				_m.LogWriteFailed = value.Bool
			}
		case run.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case run.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case run.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_runs", value)
			} else if value.Valid {
				_m.task_runs = new(int)
				*_m.task_runs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Run.
// This includes values selected through modifiers, order, etc.
func (_m *Run) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Run entity.
func (_m *Run) QueryTask() *TaskQuery {
	return NewRunClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Run.
// Note that you need to call Run.Unwrap() before calling this method if this Run
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Run) Update() *RunUpdateOne {
	return NewRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Run entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Run) Unwrap() *Run {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Run is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Run) String() string {
	var builder strings.Builder
	builder.WriteString("Run(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trigger=")
	builder.WriteString(fmt.Sprintf("%v", _m.Trigger))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ExitCode; v != nil {
		builder.WriteString("exit_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("error_summary=")
	builder.WriteString(_m.ErrorSummary)
	builder.WriteString(", ")
	builder.WriteString("stdout=")
	builder.WriteString(_m.Stdout)
	builder.WriteString(", ")
	builder.WriteString("stderr=")
	builder.WriteString(_m.Stderr)
	builder.WriteString(", ")
	builder.WriteString("log_archive_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogArchiveStatus))
	builder.WriteString(", ")
	if v := _m.LogSizeBytes; v != nil {
		builder.WriteString("log_size_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("log_write_failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.LogWriteFailed))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Runs is a parsable slice of Run.
type Runs []*Run
