// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunCreate is the builder for creating a Run entity.
type RunCreate struct {
	config
	mutation *RunMutation
	hooks    []Hook
}

// SetTrigger sets the "trigger" field.
func (rc *RunCreate) SetTrigger(r run.Trigger) *RunCreate {
	rc.mutation.SetTrigger(r)
	return rc
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (rc *RunCreate) SetNillableTrigger(r *run.Trigger) *RunCreate {
	if r != nil {
		rc.SetTrigger(*r)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *RunCreate) SetStatus(r run.Status) *RunCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *RunCreate) SetNillableStatus(r *run.Status) *RunCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// SetExitCode sets the "exit_code" field.
func (rc *RunCreate) SetExitCode(i int) *RunCreate {
	rc.mutation.SetExitCode(i)
	return rc
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (rc *RunCreate) SetNillableExitCode(i *int) *RunCreate {
	if i != nil {
		rc.SetExitCode(*i)
	}
	return rc
}

// SetStartedAt sets the "started_at" field.
func (rc *RunCreate) SetStartedAt(t time.Time) *RunCreate {
	rc.mutation.SetStartedAt(t)
	return rc
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (rc *RunCreate) SetNillableStartedAt(t *time.Time) *RunCreate {
	if t != nil {
		rc.SetStartedAt(*t)
	}
	return rc
}

// SetFinishedAt sets the "finished_at" field.
func (rc *RunCreate) SetFinishedAt(t time.Time) *RunCreate {
	rc.mutation.SetFinishedAt(t)
	return rc
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (rc *RunCreate) SetNillableFinishedAt(t *time.Time) *RunCreate {
	if t != nil {
		rc.SetFinishedAt(*t)
	}
	return rc
}

// SetDurationMs sets the "duration_ms" field.
func (rc *RunCreate) SetDurationMs(i int64) *RunCreate {
	rc.mutation.SetDurationMs(i)
	return rc
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (rc *RunCreate) SetNillableDurationMs(i *int64) *RunCreate {
	if i != nil {
		rc.SetDurationMs(*i)
	}
	return rc
}

// SetErrorSummary sets the "error_summary" field.
func (rc *RunCreate) SetErrorSummary(s string) *RunCreate {
	rc.mutation.SetErrorSummary(s)
	return rc
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (rc *RunCreate) SetNillableErrorSummary(s *string) *RunCreate {
	if s != nil {
		rc.SetErrorSummary(*s)
	}
	return rc
}

// SetStdout sets the "stdout" field.
func (rc *RunCreate) SetStdout(s string) *RunCreate {
	rc.mutation.SetStdout(s)
	return rc
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (rc *RunCreate) SetNillableStdout(s *string) *RunCreate {
	if s != nil {
		rc.SetStdout(*s)
	}
	return rc
}

// SetStderr sets the "stderr" field.
func (rc *RunCreate) SetStderr(s string) *RunCreate {
	rc.mutation.SetStderr(s)
	return rc
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (rc *RunCreate) SetNillableStderr(s *string) *RunCreate {
	if s != nil {
		rc.SetStderr(*s)
	}
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RunCreate) SetCreatedAt(t time.Time) *RunCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RunCreate) SetNillableCreatedAt(t *time.Time) *RunCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RunCreate) SetUpdatedAt(t time.Time) *RunCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RunCreate) SetNillableUpdatedAt(t *time.Time) *RunCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (rc *RunCreate) SetTaskID(id int) *RunCreate {
	rc.mutation.SetTaskID(id)
	return rc
}

// SetTask sets the "task" edge to the Task entity.
func (rc *RunCreate) SetTask(t *Task) *RunCreate {
	return rc.SetTaskID(t.ID)
}

// Mutation returns the RunMutation object of the builder.
func (rc *RunCreate) Mutation() *RunMutation {
	return rc.mutation
}

// Save creates the Run in the database.
func (rc *RunCreate) Save(ctx context.Context) (*Run, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RunCreate) SaveX(ctx context.Context) *Run {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RunCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RunCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RunCreate) defaults() {
	if _, ok := rc.mutation.Trigger(); !ok {
		v := run.DefaultTrigger
		rc.mutation.SetTrigger(v)
	}
	if _, ok := rc.mutation.Status(); !ok {
		v := run.DefaultStatus
		rc.mutation.SetStatus(v)
	}
	if _, ok := rc.mutation.StartedAt(); !ok {
		v := run.DefaultStartedAt()
		rc.mutation.SetStartedAt(v)
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := run.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := run.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RunCreate) check() error {
	if _, ok := rc.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "Run.trigger"`)}
	}
	if v, ok := rc.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Run.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Run.started_at"`)}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Run.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Run.updated_at"`)}
	}
	if _, ok := rc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Run.task"`)}
	}
	return nil
}

func (rc *RunCreate) sqlSave(ctx context.Context) (*Run, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RunCreate) createSpec() (*Run, *sqlgraph.CreateSpec) {
	var (
		_node = &Run{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(run.Table, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.ExitCode(); ok {
		_spec.SetField(run.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = &value
	}
	if value, ok := rc.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := rc.mutation.FinishedAt(); ok {
		_spec.SetField(run.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := rc.mutation.DurationMs(); ok {
		_spec.SetField(run.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := rc.mutation.ErrorSummary(); ok {
		_spec.SetField(run.FieldErrorSummary, field.TypeString, value)
		_node.ErrorSummary = value
	}
	if value, ok := rc.mutation.Stdout(); ok {
		_spec.SetField(run.FieldStdout, field.TypeString, value)
		_node.Stdout = value
	}
	if value, ok := rc.mutation.Stderr(); ok {
		_spec.SetField(run.FieldStderr, field.TypeString, value)
		_node.Stderr = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(run.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_runs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RunCreateBulk is the builder for creating many Run entities in bulk.
type RunCreateBulk struct {
	config
	err      error
	builders []*RunCreate
}

// Save creates the Run entities in the database.
func (rcb *RunCreateBulk) Save(ctx context.Context) ([]*Run, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Run, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RunCreateBulk) SaveX(ctx context.Context) []*Run {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RunCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RunCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
