// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RunCreate is the builder for creating a Run entity.
type RunCreate struct {
	config
	mutation *RunMutation
	hooks    []Hook
}

// SetTrigger sets the "trigger" field.
func (_c *RunCreate) SetTrigger(v run.Trigger) *RunCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_c *RunCreate) SetNillableTrigger(v *run.Trigger) *RunCreate {
	if v != nil {
		_c.SetTrigger(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RunCreate) SetStatus(v run.Status) *RunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RunCreate) SetNillableStatus(v *run.Status) *RunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *RunCreate) SetExitCode(v int) *RunCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *RunCreate) SetNillableExitCode(v *int) *RunCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *RunCreate) SetStartedAt(v time.Time) *RunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableStartedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *RunCreate) SetFinishedAt(v time.Time) *RunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableFinishedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RunCreate) SetDurationMs(v int64) *RunCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RunCreate) SetNillableDurationMs(v *int64) *RunCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorSummary sets the "error_summary" field.
func (_c *RunCreate) SetErrorSummary(v string) *RunCreate {
	_c.mutation.SetErrorSummary(v)
	return _c
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (_c *RunCreate) SetNillableErrorSummary(v *string) *RunCreate {
	if v != nil {
		_c.SetErrorSummary(*v)
	}
	return _c
}

// SetStdout sets the "stdout" field.
func (_c *RunCreate) SetStdout(v string) *RunCreate {
	_c.mutation.SetStdout(v)
	return _c
}

// SetNillableStdout sets the "stdout" field if the given value is not nil.
func (_c *RunCreate) SetNillableStdout(v *string) *RunCreate {
	if v != nil {
		_c.SetStdout(*v)
	}
	return _c
}

// SetStderr sets the "stderr" field.
func (_c *RunCreate) SetStderr(v string) *RunCreate {
	_c.mutation.SetStderr(v)
	return _c
}

// SetNillableStderr sets the "stderr" field if the given value is not nil.
func (_c *RunCreate) SetNillableStderr(v *string) *RunCreate {
	if v != nil {
		_c.SetStderr(*v)
	}
	return _c
}

// SetLogArchiveStatus sets the "log_archive_status" field.
func (_c *RunCreate) SetLogArchiveStatus(v run.LogArchiveStatus) *RunCreate {
	_c.mutation.SetLogArchiveStatus(v)
	return _c
}

// SetNillableLogArchiveStatus sets the "log_archive_status" field if the given value is not nil.
func (_c *RunCreate) SetNillableLogArchiveStatus(v *run.LogArchiveStatus) *RunCreate {
	if v != nil {
		_c.SetLogArchiveStatus(*v)
	}
	return _c
}

// SetLogSizeBytes sets the "log_size_bytes" field.
func (_c *RunCreate) SetLogSizeBytes(v int64) *RunCreate {
	_c.mutation.SetLogSizeBytes(v)
	return _c
}

// SetNillableLogSizeBytes sets the "log_size_bytes" field if the given value is not nil.
func (_c *RunCreate) SetNillableLogSizeBytes(v *int64) *RunCreate {
	if v != nil {
		_c.SetLogSizeBytes(*v)
	}
	return _c
}

// SetLogWriteFailed sets the "log_write_failed" field.
func (_c *RunCreate) SetLogWriteFailed(v bool) *RunCreate {
	_c.mutation.SetLogWriteFailed(v)
	return _c
}

// SetNillableLogWriteFailed sets the "log_write_failed" field if the given value is not nil.
func (_c *RunCreate) SetNillableLogWriteFailed(v *bool) *RunCreate {
	if v != nil {
		_c.SetLogWriteFailed(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RunCreate) SetCreatedAt(v time.Time) *RunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableCreatedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RunCreate) SetUpdatedAt(v time.Time) *RunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RunCreate) SetNillableUpdatedAt(v *time.Time) *RunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *RunCreate) SetTaskID(id int) *RunCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *RunCreate) SetTask(v *Task) *RunCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the RunMutation object of the builder.
func (_c *RunCreate) Mutation() *RunMutation {
	return _c.mutation
}

// Save creates the Run in the database.
func (_c *RunCreate) Save(ctx context.Context) (*Run, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunCreate) SaveX(ctx context.Context) *Run {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunCreate) defaults() {
	if _, ok := _c.mutation.Trigger(); !ok {
		v := run.DefaultTrigger
		_c.mutation.SetTrigger(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := run.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := run.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.LogArchiveStatus(); !ok {
		v := run.DefaultLogArchiveStatus
		_c.mutation.SetLogArchiveStatus(v)
	}
	if _, ok := _c.mutation.LogWriteFailed(); !ok {
		v := run.DefaultLogWriteFailed
		_c.mutation.SetLogWriteFailed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := run.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := run.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunCreate) check() error {
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "Run.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Run.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Run.started_at"`)}
	}
	if _, ok := _c.mutation.LogArchiveStatus(); !ok {
		return &ValidationError{Name: "log_archive_status", err: errors.New(`ent: missing required field "Run.log_archive_status"`)}
	}
	if v, ok := _c.mutation.LogArchiveStatus(); ok {
		if err := run.LogArchiveStatusValidator(v); err != nil {
			return &ValidationError{Name: "log_archive_status", err: fmt.Errorf(`ent: validator failed for field "Run.log_archive_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogWriteFailed(); !ok {
		return &ValidationError{Name: "log_write_failed", err: errors.New(`ent: missing required field "Run.log_write_failed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Run.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Run.updated_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Run.task"`)}
	}
	return nil
}

func (_c *RunCreate) sqlSave(ctx context.Context) (*Run, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunCreate) createSpec() (*Run, *sqlgraph.CreateSpec) {
	var (
		_node = &Run{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(run.Table, sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(run.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(run.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(run.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.ErrorSummary(); ok {
		_spec.SetField(run.FieldErrorSummary, field.TypeString, value)
		_node.ErrorSummary = value
	}
	if value, ok := _c.mutation.Stdout(); ok {
		_spec.SetField(run.FieldStdout, field.TypeString, value)
		_node.Stdout = value
	}
	if value, ok := _c.mutation.Stderr(); ok {
		_spec.SetField(run.FieldStderr, field.TypeString, value)
		_node.Stderr = value
	}
	if value, ok := _c.mutation.LogArchiveStatus(); ok {
		_spec.SetField(run.FieldLogArchiveStatus, field.TypeEnum, value)
		_node.LogArchiveStatus = value
	}
	if value, ok := _c.mutation.LogSizeBytes(); ok {
		_spec.SetField(run.FieldLogSizeBytes, field.TypeInt64, value)
		_node.LogSizeBytes = &value
	}
	if value, ok := _c.mutation.LogWriteFailed(); ok {
		_spec.SetField(run.FieldLogWriteFailed, field.TypeBool, value)
		_node.LogWriteFailed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(run.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   run.TaskTable,
			Columns: []string{run.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_runs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RunCreateBulk is the builder for creating many Run entities in bulk.
type RunCreateBulk struct {
	config
	err      error
	builders []*RunCreate
}

// Save creates the Run entities in the database.
func (_c *RunCreateBulk) Save(ctx context.Context) ([]*Run, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Run, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunCreateBulk) SaveX(ctx context.Context) []*Run {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
