// Code generated by ent, DO NOT EDIT.

package ent

import (
	"taskdaemon/internal/data/ent/admin"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/schema"
	"taskdaemon/internal/data/ent/session"
	"taskdaemon/internal/data/ent/task"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescSingletonKey is the schema descriptor for singleton_key field.
	adminDescSingletonKey := adminFields[0].Descriptor()
	// admin.SingletonKeyValidator is a validator for the "singleton_key" field. It is called by the builders before save.
	admin.SingletonKeyValidator = adminDescSingletonKey.Validators[0].(func(string) error)
	// adminDescUsername is the schema descriptor for username field.
	adminDescUsername := adminFields[1].Descriptor()
	// admin.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	admin.UsernameValidator = adminDescUsername.Validators[0].(func(string) error)
	// adminDescActive is the schema descriptor for active field.
	adminDescActive := adminFields[3].Descriptor()
	// admin.DefaultActive holds the default value on creation for the active field.
	admin.DefaultActive = adminDescActive.Default.(bool)
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminFields[4].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminFields[5].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	runFields := schema.Run{}.Fields()
	_ = runFields
	// runDescStartedAt is the schema descriptor for started_at field.
	runDescStartedAt := runFields[3].Descriptor()
	// run.DefaultStartedAt holds the default value on creation for the started_at field.
	run.DefaultStartedAt = runDescStartedAt.Default.(func() time.Time)
	// runDescCreatedAt is the schema descriptor for created_at field.
	runDescCreatedAt := runFields[9].Descriptor()
	// run.DefaultCreatedAt holds the default value on creation for the created_at field.
	run.DefaultCreatedAt = runDescCreatedAt.Default.(func() time.Time)
	// runDescUpdatedAt is the schema descriptor for updated_at field.
	runDescUpdatedAt := runFields[10].Descriptor()
	// run.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	run.DefaultUpdatedAt = runDescUpdatedAt.Default.(func() time.Time)
	// run.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	run.UpdateDefaultUpdatedAt = runDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[5].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[6].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescName is the schema descriptor for name field.
	taskDescName := taskFields[0].Descriptor()
	// task.NameValidator is a validator for the "name" field. It is called by the builders before save.
	task.NameValidator = taskDescName.Validators[0].(func(string) error)
	// taskDescEnabled is the schema descriptor for enabled field.
	taskDescEnabled := taskFields[2].Descriptor()
	// task.DefaultEnabled holds the default value on creation for the enabled field.
	task.DefaultEnabled = taskDescEnabled.Default.(bool)
	// taskDescTimezone is the schema descriptor for timezone field.
	taskDescTimezone := taskFields[4].Descriptor()
	// task.DefaultTimezone holds the default value on creation for the timezone field.
	task.DefaultTimezone = taskDescTimezone.Default.(string)
	// taskDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	taskDescTimeoutSeconds := taskFields[7].Descriptor()
	// task.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	task.DefaultTimeoutSeconds = taskDescTimeoutSeconds.Default.(int)
	// task.TimeoutSecondsValidator is a validator for the "timeout_seconds" field. It is called by the builders before save.
	task.TimeoutSecondsValidator = taskDescTimeoutSeconds.Validators[0].(func(int) error)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[9].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[10].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
}
