// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/predicate"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TaskUpdate) SetName(v string) *TaskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableName(v *string) *TaskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TaskUpdate) SetEnabled(v bool) *TaskUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEnabled(v *bool) *TaskUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *TaskUpdate) SetCronExpression(v string) *TaskUpdate {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCronExpression(v *string) *TaskUpdate {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *TaskUpdate) ClearCronExpression() *TaskUpdate {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TaskUpdate) SetTimezone(v string) *TaskUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTimezone(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetRunnerType sets the "runner_type" field.
func (_u *TaskUpdate) SetRunnerType(v task.RunnerType) *TaskUpdate {
	_u.mutation.SetRunnerType(v)
	return _u
}

// SetNillableRunnerType sets the "runner_type" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableRunnerType(v *task.RunnerType) *TaskUpdate {
	if v != nil {
		_u.SetRunnerType(*v)
	}
	return _u
}

// SetRunnerConfig sets the "runner_config" field.
func (_u *TaskUpdate) SetRunnerConfig(v map[string]interface{}) *TaskUpdate {
	_u.mutation.SetRunnerConfig(v)
	return _u
}

// ClearRunnerConfig clears the value of the "runner_config" field.
func (_u *TaskUpdate) ClearRunnerConfig() *TaskUpdate {
	_u.mutation.ClearRunnerConfig()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *TaskUpdate) SetTimeoutSeconds(v int) *TaskUpdate {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTimeoutSeconds(v *int) *TaskUpdate {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *TaskUpdate) AddTimeoutSeconds(v int) *TaskUpdate {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetOverlapPolicy sets the "overlap_policy" field.
func (_u *TaskUpdate) SetOverlapPolicy(v task.OverlapPolicy) *TaskUpdate {
	_u.mutation.SetOverlapPolicy(v)
	return _u
}

// SetNillableOverlapPolicy sets the "overlap_policy" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableOverlapPolicy(v *task.OverlapPolicy) *TaskUpdate {
	if v != nil {
		_u.SetOverlapPolicy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRunIDs adds the "runs" edge to the Run entity by IDs.
func (_u *TaskUpdate) AddRunIDs(ids ...int) *TaskUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the Run entity.
func (_u *TaskUpdate) AddRuns(v ...*Run) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearRuns clears all "runs" edges to the Run entity.
func (_u *TaskUpdate) ClearRuns() *TaskUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to Run entities by IDs.
func (_u *TaskUpdate) RemoveRunIDs(ids ...int) *TaskUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to Run entities.
func (_u *TaskUpdate) RemoveRuns(v ...*Run) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunnerType(); ok {
		if err := task.RunnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "runner_type", err: fmt.Errorf(`ent: validator failed for field "Task.runner_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutSeconds(); ok {
		if err := task.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Task.timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OverlapPolicy(); ok {
		if err := task.OverlapPolicyValidator(v); err != nil {
			return &ValidationError{Name: "overlap_policy", err: fmt.Errorf(`ent: validator failed for field "Task.overlap_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(task.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(task.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(task.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(task.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunnerType(); ok {
		_spec.SetField(task.FieldRunnerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RunnerConfig(); ok {
		_spec.SetField(task.FieldRunnerConfig, field.TypeJSON, value)
	}
	if _u.mutation.RunnerConfigCleared() {
		_spec.ClearField(task.FieldRunnerConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(task.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(task.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OverlapPolicy(); ok {
		_spec.SetField(task.FieldOverlapPolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetName sets the "name" field.
func (_u *TaskUpdateOne) SetName(v string) *TaskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableName(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TaskUpdateOne) SetEnabled(v bool) *TaskUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEnabled(v *bool) *TaskUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *TaskUpdateOne) SetCronExpression(v string) *TaskUpdateOne {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCronExpression(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// ClearCronExpression clears the value of the "cron_expression" field.
func (_u *TaskUpdateOne) ClearCronExpression() *TaskUpdateOne {
	_u.mutation.ClearCronExpression()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TaskUpdateOne) SetTimezone(v string) *TaskUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTimezone(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetRunnerType sets the "runner_type" field.
func (_u *TaskUpdateOne) SetRunnerType(v task.RunnerType) *TaskUpdateOne {
	_u.mutation.SetRunnerType(v)
	return _u
}

// SetNillableRunnerType sets the "runner_type" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableRunnerType(v *task.RunnerType) *TaskUpdateOne {
	if v != nil {
		_u.SetRunnerType(*v)
	}
	return _u
}

// SetRunnerConfig sets the "runner_config" field.
func (_u *TaskUpdateOne) SetRunnerConfig(v map[string]interface{}) *TaskUpdateOne {
	_u.mutation.SetRunnerConfig(v)
	return _u
}

// ClearRunnerConfig clears the value of the "runner_config" field.
func (_u *TaskUpdateOne) ClearRunnerConfig() *TaskUpdateOne {
	_u.mutation.ClearRunnerConfig()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *TaskUpdateOne) SetTimeoutSeconds(v int) *TaskUpdateOne {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTimeoutSeconds(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *TaskUpdateOne) AddTimeoutSeconds(v int) *TaskUpdateOne {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetOverlapPolicy sets the "overlap_policy" field.
func (_u *TaskUpdateOne) SetOverlapPolicy(v task.OverlapPolicy) *TaskUpdateOne {
	_u.mutation.SetOverlapPolicy(v)
	return _u
}

// SetNillableOverlapPolicy sets the "overlap_policy" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableOverlapPolicy(v *task.OverlapPolicy) *TaskUpdateOne {
	if v != nil {
		_u.SetOverlapPolicy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRunIDs adds the "runs" edge to the Run entity by IDs.
func (_u *TaskUpdateOne) AddRunIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the Run entity.
func (_u *TaskUpdateOne) AddRuns(v ...*Run) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearRuns clears all "runs" edges to the Run entity.
func (_u *TaskUpdateOne) ClearRuns() *TaskUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to Run entities by IDs.
func (_u *TaskUpdateOne) RemoveRunIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to Run entities.
func (_u *TaskUpdateOne) RemoveRuns(v ...*Run) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunnerType(); ok {
		if err := task.RunnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "runner_type", err: fmt.Errorf(`ent: validator failed for field "Task.runner_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutSeconds(); ok {
		if err := task.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Task.timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OverlapPolicy(); ok {
		if err := task.OverlapPolicyValidator(v); err != nil {
			return &ValidationError{Name: "overlap_policy", err: fmt.Errorf(`ent: validator failed for field "Task.overlap_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(task.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(task.FieldCronExpression, field.TypeString, value)
	}
	if _u.mutation.CronExpressionCleared() {
		_spec.ClearField(task.FieldCronExpression, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(task.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunnerType(); ok {
		_spec.SetField(task.FieldRunnerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RunnerConfig(); ok {
		_spec.SetField(task.FieldRunnerConfig, field.TypeJSON, value)
	}
	if _u.mutation.RunnerConfigCleared() {
		_spec.ClearField(task.FieldRunnerConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(task.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(task.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OverlapPolicy(); ok {
		_spec.SetField(task.FieldOverlapPolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
