// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TaskCreate) SetName(s string) *TaskCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TaskCreate) SetDescription(s string) *TaskCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *TaskCreate) SetNillableDescription(s *string) *TaskCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetEnabled sets the "enabled" field.
func (tc *TaskCreate) SetEnabled(b bool) *TaskCreate {
	tc.mutation.SetEnabled(b)
	return tc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tc *TaskCreate) SetNillableEnabled(b *bool) *TaskCreate {
	if b != nil {
		tc.SetEnabled(*b)
	}
	return tc
}

// SetCronExpression sets the "cron_expression" field.
func (tc *TaskCreate) SetCronExpression(s string) *TaskCreate {
	tc.mutation.SetCronExpression(s)
	return tc
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCronExpression(s *string) *TaskCreate {
	if s != nil {
		tc.SetCronExpression(*s)
	}
	return tc
}

// SetTimezone sets the "timezone" field.
func (tc *TaskCreate) SetTimezone(s string) *TaskCreate {
	tc.mutation.SetTimezone(s)
	return tc
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (tc *TaskCreate) SetNillableTimezone(s *string) *TaskCreate {
	if s != nil {
		tc.SetTimezone(*s)
	}
	return tc
}

// SetRunnerType sets the "runner_type" field.
func (tc *TaskCreate) SetRunnerType(tt task.RunnerType) *TaskCreate {
	tc.mutation.SetRunnerType(tt)
	return tc
}

// SetNillableRunnerType sets the "runner_type" field if the given value is not nil.
func (tc *TaskCreate) SetNillableRunnerType(tt *task.RunnerType) *TaskCreate {
	if tt != nil {
		tc.SetRunnerType(*tt)
	}
	return tc
}

// SetRunnerConfig sets the "runner_config" field.
func (tc *TaskCreate) SetRunnerConfig(m map[string]interface{}) *TaskCreate {
	tc.mutation.SetRunnerConfig(m)
	return tc
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (tc *TaskCreate) SetTimeoutSeconds(i int) *TaskCreate {
	tc.mutation.SetTimeoutSeconds(i)
	return tc
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (tc *TaskCreate) SetNillableTimeoutSeconds(i *int) *TaskCreate {
	if i != nil {
		tc.SetTimeoutSeconds(*i)
	}
	return tc
}

// SetOverlapPolicy sets the "overlap_policy" field.
func (tc *TaskCreate) SetOverlapPolicy(tp task.OverlapPolicy) *TaskCreate {
	tc.mutation.SetOverlapPolicy(tp)
	return tc
}

// SetNillableOverlapPolicy sets the "overlap_policy" field if the given value is not nil.
func (tc *TaskCreate) SetNillableOverlapPolicy(tp *task.OverlapPolicy) *TaskCreate {
	if tp != nil {
		tc.SetOverlapPolicy(*tp)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TaskCreate) SetCreatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCreatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TaskCreate) SetUpdatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableUpdatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// AddRunIDs adds the "runs" edge to the Run entity by IDs.
func (tc *TaskCreate) AddRunIDs(ids ...int) *TaskCreate {
	tc.mutation.AddRunIDs(ids...)
	return tc
}

// AddRuns adds the "runs" edges to the Run entity.
func (tc *TaskCreate) AddRuns(r ...*Run) *TaskCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tc.AddRunIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.Enabled(); !ok {
		v := task.DefaultEnabled
		tc.mutation.SetEnabled(v)
	}
	if _, ok := tc.mutation.Timezone(); !ok {
		v := task.DefaultTimezone
		tc.mutation.SetTimezone(v)
	}
	if _, ok := tc.mutation.RunnerType(); !ok {
		v := task.DefaultRunnerType
		tc.mutation.SetRunnerType(v)
	}
	if _, ok := tc.mutation.TimeoutSeconds(); !ok {
		v := task.DefaultTimeoutSeconds
		tc.mutation.SetTimeoutSeconds(v)
	}
	if _, ok := tc.mutation.OverlapPolicy(); !ok {
		v := task.DefaultOverlapPolicy
		tc.mutation.SetOverlapPolicy(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Task.name"`)}
	}
	if v, ok := tc.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Task.enabled"`)}
	}
	if _, ok := tc.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Task.timezone"`)}
	}
	if _, ok := tc.mutation.RunnerType(); !ok {
		return &ValidationError{Name: "runner_type", err: errors.New(`ent: missing required field "Task.runner_type"`)}
	}
	if v, ok := tc.mutation.RunnerType(); ok {
		if err := task.RunnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "runner_type", err: fmt.Errorf(`ent: validator failed for field "Task.runner_type": %w`, err)}
		}
	}
	if _, ok := tc.mutation.TimeoutSeconds(); !ok {
		return &ValidationError{Name: "timeout_seconds", err: errors.New(`ent: missing required field "Task.timeout_seconds"`)}
	}
	if v, ok := tc.mutation.TimeoutSeconds(); ok {
		if err := task.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Task.timeout_seconds": %w`, err)}
		}
	}
	if _, ok := tc.mutation.OverlapPolicy(); !ok {
		return &ValidationError{Name: "overlap_policy", err: errors.New(`ent: missing required field "Task.overlap_policy"`)}
	}
	if v, ok := tc.mutation.OverlapPolicy(); ok {
		if err := task.OverlapPolicyValidator(v); err != nil {
			return &ValidationError{Name: "overlap_policy", err: fmt.Errorf(`ent: validator failed for field "Task.overlap_policy": %w`, err)}
		}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.Enabled(); ok {
		_spec.SetField(task.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := tc.mutation.CronExpression(); ok {
		_spec.SetField(task.FieldCronExpression, field.TypeString, value)
		_node.CronExpression = value
	}
	if value, ok := tc.mutation.Timezone(); ok {
		_spec.SetField(task.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := tc.mutation.RunnerType(); ok {
		_spec.SetField(task.FieldRunnerType, field.TypeEnum, value)
		_node.RunnerType = value
	}
	if value, ok := tc.mutation.RunnerConfig(); ok {
		_spec.SetField(task.FieldRunnerConfig, field.TypeJSON, value)
		_node.RunnerConfig = value
	}
	if value, ok := tc.mutation.TimeoutSeconds(); ok {
		_spec.SetField(task.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = value
	}
	if value, ok := tc.mutation.OverlapPolicy(); ok {
		_spec.SetField(task.FieldOverlapPolicy, field.TypeEnum, value)
		_node.OverlapPolicy = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
