// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskdaemon/internal/data/ent/run"
	"taskdaemon/internal/data/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TaskCreate) SetName(v string) *TaskCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TaskCreate) SetDescription(v string) *TaskCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TaskCreate) SetNillableDescription(v *string) *TaskCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *TaskCreate) SetEnabled(v bool) *TaskCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TaskCreate) SetNillableEnabled(v *bool) *TaskCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCronExpression sets the "cron_expression" field.
func (_c *TaskCreate) SetCronExpression(v string) *TaskCreate {
	_c.mutation.SetCronExpression(v)
	return _c
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCronExpression(v *string) *TaskCreate {
	if v != nil {
		_c.SetCronExpression(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *TaskCreate) SetTimezone(v string) *TaskCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTimezone(v *string) *TaskCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetRunnerType sets the "runner_type" field.
func (_c *TaskCreate) SetRunnerType(v task.RunnerType) *TaskCreate {
	_c.mutation.SetRunnerType(v)
	return _c
}

// SetNillableRunnerType sets the "runner_type" field if the given value is not nil.
func (_c *TaskCreate) SetNillableRunnerType(v *task.RunnerType) *TaskCreate {
	if v != nil {
		_c.SetRunnerType(*v)
	}
	return _c
}

// SetRunnerConfig sets the "runner_config" field.
func (_c *TaskCreate) SetRunnerConfig(v map[string]interface{}) *TaskCreate {
	_c.mutation.SetRunnerConfig(v)
	return _c
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_c *TaskCreate) SetTimeoutSeconds(v int) *TaskCreate {
	_c.mutation.SetTimeoutSeconds(v)
	return _c
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTimeoutSeconds(v *int) *TaskCreate {
	if v != nil {
		_c.SetTimeoutSeconds(*v)
	}
	return _c
}

// SetOverlapPolicy sets the "overlap_policy" field.
func (_c *TaskCreate) SetOverlapPolicy(v task.OverlapPolicy) *TaskCreate {
	_c.mutation.SetOverlapPolicy(v)
	return _c
}

// SetNillableOverlapPolicy sets the "overlap_policy" field if the given value is not nil.
func (_c *TaskCreate) SetNillableOverlapPolicy(v *task.OverlapPolicy) *TaskCreate {
	if v != nil {
		_c.SetOverlapPolicy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskCreate) SetUpdatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddRunIDs adds the "runs" edge to the Run entity by IDs.
func (_c *TaskCreate) AddRunIDs(ids ...int) *TaskCreate {
	_c.mutation.AddRunIDs(ids...)
	return _c
}

// AddRuns adds the "runs" edges to the Run entity.
func (_c *TaskCreate) AddRuns(v ...*Run) *TaskCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRunIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := task.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := task.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.RunnerType(); !ok {
		v := task.DefaultRunnerType
		_c.mutation.SetRunnerType(v)
	}
	if _, ok := _c.mutation.TimeoutSeconds(); !ok {
		v := task.DefaultTimeoutSeconds
		_c.mutation.SetTimeoutSeconds(v)
	}
	if _, ok := _c.mutation.OverlapPolicy(); !ok {
		v := task.DefaultOverlapPolicy
		_c.mutation.SetOverlapPolicy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Task.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Task.enabled"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Task.timezone"`)}
	}
	if _, ok := _c.mutation.RunnerType(); !ok {
		return &ValidationError{Name: "runner_type", err: errors.New(`ent: missing required field "Task.runner_type"`)}
	}
	if v, ok := _c.mutation.RunnerType(); ok {
		if err := task.RunnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "runner_type", err: fmt.Errorf(`ent: validator failed for field "Task.runner_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeoutSeconds(); !ok {
		return &ValidationError{Name: "timeout_seconds", err: errors.New(`ent: missing required field "Task.timeout_seconds"`)}
	}
	if v, ok := _c.mutation.TimeoutSeconds(); ok {
		if err := task.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Task.timeout_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OverlapPolicy(); !ok {
		return &ValidationError{Name: "overlap_policy", err: errors.New(`ent: missing required field "Task.overlap_policy"`)}
	}
	if v, ok := _c.mutation.OverlapPolicy(); ok {
		if err := task.OverlapPolicyValidator(v); err != nil {
			return &ValidationError{Name: "overlap_policy", err: fmt.Errorf(`ent: validator failed for field "Task.overlap_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(task.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CronExpression(); ok {
		_spec.SetField(task.FieldCronExpression, field.TypeString, value)
		_node.CronExpression = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(task.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.RunnerType(); ok {
		_spec.SetField(task.FieldRunnerType, field.TypeEnum, value)
		_node.RunnerType = value
	}
	if value, ok := _c.mutation.RunnerConfig(); ok {
		_spec.SetField(task.FieldRunnerConfig, field.TypeJSON, value)
		_node.RunnerConfig = value
	}
	if value, ok := _c.mutation.TimeoutSeconds(); ok {
		_spec.SetField(task.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = value
	}
	if value, ok := _c.mutation.OverlapPolicy(); ok {
		_spec.SetField(task.FieldOverlapPolicy, field.TypeEnum, value)
		_node.OverlapPolicy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.RunsTable,
			Columns: []string{task.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
