// Code generated by ent, DO NOT EDIT.

package audiorecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the audiorecord type in the database.
	Label = "audio_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceKind holds the string denoting the source_kind field in the database.
	FieldSourceKind = "source_kind"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldOriginalFilename holds the string denoting the original_filename field in the database.
	FieldOriginalFilename = "original_filename"
	// FieldStoredPath holds the string denoting the stored_path field in the database.
	FieldStoredPath = "stored_path"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldErrorSummary holds the string denoting the error_summary field in the database.
	FieldErrorSummary = "error_summary"
	// FieldPlayedAt holds the string denoting the played_at field in the database.
	FieldPlayedAt = "played_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the audiorecord in the database.
	Table = "audio_records"
)

// Columns holds all SQL columns for audiorecord fields.
var Columns = []string{
	FieldID,
	FieldSourceKind,
	FieldSource,
	FieldSourceURL,
	FieldOriginalFilename,
	FieldStoredPath,
	FieldMimeType,
	FieldSizeBytes,
	FieldSha256,
	FieldStatus,
	FieldErrorSummary,
	FieldPlayedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StoredPathValidator is a validator for the "stored_path" field. It is called by the builders before save.
	StoredPathValidator func(string) error
	// SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	SizeBytesValidator func(int64) error
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// SourceKind defines the type for the "source_kind" enum field.
type SourceKind string

// SourceKindURL is the default value of the SourceKind enum.
const DefaultSourceKind = SourceKindURL

// SourceKind values.
const (
	SourceKindURL    SourceKind = "url"
	SourceKindUpload SourceKind = "upload"
)

func (sk SourceKind) String() string {
	return string(sk)
}

// SourceKindValidator is a validator for the "source_kind" field enum values. It is called by the builders before save.
func SourceKindValidator(sk SourceKind) error {
	switch sk {
	case SourceKindURL, SourceKindUpload:
		return nil
	default:
		return fmt.Errorf("audiorecord: invalid enum value for source_kind field: %q", sk)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusReceived is the default value of the Status enum.
const DefaultStatus = StatusReceived

// Status values.
const (
	StatusReceived      Status = "received"
	StatusQueued        Status = "queued"
	StatusPlaying       Status = "playing"
	StatusPlayed        Status = "played"
	StatusFailed        Status = "failed"
	StatusSkipped       Status = "skipped"
	StatusQueuedSkipped Status = "queued_skipped"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusReceived, StatusQueued, StatusPlaying, StatusPlayed, StatusFailed, StatusSkipped, StatusQueuedSkipped:
		return nil
	default:
		return fmt.Errorf("audiorecord: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AudioRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceKind orders the results by the source_kind field.
func BySourceKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceKind, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByOriginalFilename orders the results by the original_filename field.
func ByOriginalFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalFilename, opts...).ToFunc()
}

// ByStoredPath orders the results by the stored_path field.
func ByStoredPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoredPath, opts...).ToFunc()
}

// ByMimeType orders the results by the mime_type field.
func ByMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMimeType, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorSummary orders the results by the error_summary field.
func ByErrorSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorSummary, opts...).ToFunc()
}

// ByPlayedAt orders the results by the played_at field.
func ByPlayedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
