// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Run is the predicate function for run builders.
type Run func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
